export const FIND_PRODUCT_BY_ID_REQUEST = 'FIND_PRODUCT_BY_ID_REQUEST';
export const FIND_PRODUCT_BY_ID_SUCCESS = 'FIND_PRODUCT_BY_ID_SUCCESS';
export const FIND_PRODUCT_BY_ID_FAILURE = 'FIND_PRODUCT_BY_ID_FAILURE';

export const FIND_PRODUCTS_REQUEST = 'FIND_PRODUCTS_REQUEST';
export const FIND_PRODUCTS_SUCCESS = 'FIND_PRODUCTS_SUCCESS';
export const FIND_PRODUCTS_FAILURE = 'FIND_PRODUCTS_FAILURE';

export const GET_TOP_SALE_REQUEST = 'GET_TOP_SALE_REQUEST';
export const GET_TOP_SALE_SUCCESS = 'GET_TOP_SALE_SUCCESS'; 
export const GET_TOP_SALE_FAILURE = 'GET_TOP_SALE_FAILURE';
